----- 시퀀스 삭제 -----
DROP SEQUENCE SEQ_SIGN;
DROP SEQUENCE SEQ_SIGN_FILE;
DROP SEQUENCE SEQ_SIGN_PATH;
DROP SEQUENCE SEQ_SIGN_REF;
DROP SEQUENCE SEQ_SIGN_COM;
DROP SEQUENCE SEQ_LEAVE;
DROP SEQUENCE SEQ_BUSINESS_TRIP;



----- 테이블 삭제 -----
DROP TABLE SIGN CASCADE CONSTRAINTS;
DROP TABLE SIGN_FILE CASCADE CONSTRAINTS;
DROP TABLE SIGN_PATH CASCADE CONSTRAINTS;
DROP TABLE SIGN_REF CASCADE CONSTRAINTS;
DROP TABLE SIGN_COM CASCADE CONSTRAINTS;
DROP TABLE LEAVE CASCADE CONSTRAINTS;
DROP TABLE BUSINESS_TRIP CASCADE CONSTRAINTS;



----- 시퀀스 생성 -----
CREATE SEQUENCE SEQ_SIGN NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SIGN_FILE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SIGN_PATH NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SIGN_REF NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SIGN_COM NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LEAVE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BUSINESS_TRIP NOCACHE NOCYCLE;



----- 테이블 생성 -----
CREATE TABLE SIGN(
    NO              NUMBER          PRIMARY KEY
    , EMP_NO        NUMBER
    , RESULT        NUMBER          NOT NULL
    , STEP          NUMBER          NOT NULL
    , TITLE         VARCHAR2(1000)  NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , ENROLL_DATE   DATE            DEFAULT SYSDATE
);
CREATE TABLE SIGN_FILE(
    NO              NUMBER          PRIMARY KEY
    , SIGN_NO       NUMBER
    , CHANGE_NAME   VARCHAR2(1000)  NOT NULL UNIQUE
    , ORIGIN_NAME   VARCHAR2(1000)  NOT NULL
    , "SIZE"        VARCHAR2(100)   NOT NULL
    , MODIFY_DATE   DATE            DEFAULT SYSDATE
);
CREATE TABLE SIGN_PATH(
    NO              NUMBER          PRIMARY KEY
    , SIGN_NO       NUMBER
    , APPROVER_NO   NUMBER
    , SIGN_SEQ      NUMBER          NOT NULL
);
CREATE TABLE SIGN_REF(
    NO              NUMBER          PRIMARY KEY
    , SIGN_NO       NUMBER
    , REF_NO        NUMBER
);
CREATE TABLE SIGN_COM(
    NO              NUMBER          PRIMARY KEY
    , SIGN_NO       NUMBER
    , "COMMENT"     VARCHAR2(4000)
);
CREATE TABLE LEAVE(
    NO              NUMBER          PRIMARY KEY
    , EMP_NO        NUMBER
    , SIGN_NO       VARCHAR2(4000)
    , TYPE          VARCHAR2(100)   NOT NULL
    , START_DATE    DATE
    , END_DATE      DATE
    , REASON        VARCHAR2(4000)  NOT NULL
);
CREATE TABLE BUSINESS_TRIP(
    NO              NUMBER          PRIMARY KEY
    , EMP_NO        NUMBER
    , PRO_NO        NUMBER
    , SIGN_NO       NUMBER
    , START_DATE    DATE
    , END_DATE      DATE
    , REASON        VARCHAR2(4000)  NOT NULL
    , DESTINATION   VARCHAR2(1000)  NOT NULL
);



----- 메일 -----
DROP SEQUENCE SEQ_MAIL;
DROP SEQUENCE SEQ_MAIL_AD;
DROP SEQUENCE SEQ_MAIL_INFO;
DROP SEQUENCE SEQ_MAIL_FILE;

DROP TABLE MAIL CASCADE CONSTRAINTS;
DROP TABLE MAIL_AD CASCADE CONSTRAINTS;
DROP TABLE MAIL_INFO CASCADE CONSTRAINTS;
DROP TABLE MAIL_FILE CASCADE CONSTRAINTS;

CREATE SEQUENCE SEQ_MAIL NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MAIL_AD NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MAIL_INFO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MAIL_FILE NOCACHE NOCYCLE;

CREATE TABLE MAIL(
    NO              NUMBER          PRIMARY KEY
    , EMP_NO        NUMBER
    , MAIL_INFO_NO  NUMBER
    , TYPE          VARCHAR2(20)    NOT NULL
    , SUBJECT       VARCHAR2(1000)  NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , "FROM"        CHAR(20)        NOT NULL
    , READ_DATE     DATE
    , WRITE_DATE    DATE            DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK (DEL_YN IN ('Y', 'N'))
);
CREATE TABLE MAIL_AD(
    NO              NUMBER          PRIMARY KEY
    , MAIL_NO       NUMBER
    , ADDRESS       CHAR(20)        NOT NULL
    , TYPE          VARCHAR2(20)    NOT NULL
);
CREATE TABLE MAIL_INFO(
    NO              NUMBER          PRIMARY KEY
    , EMP_NO        NUMBER
    , IMAP_AD       VARCHAR2(1000)  NOT NULL
    , IMAP_PORT     VARCHAR2(1000)  NOT NULL
    , SMTP_AD       VARCHAR2(1000)  NOT NULL
    , SMTP_PORT     VARCHAR2(1000)  NOT NULL
    , ACCOUNT       CHAR(20)        NOT NULL
    , PWD           CHAR(15)        NOT NULL
    , ENROLL_DATE   DATE            DEFAULT SYSDATE
);
CREATE TABLE MAIL_FILE(
    NO              NUMBER          PRIMARY KEY
    , MAIL_NO       NUMBER
    , CHANGE_NAME   VARCHAR2(1000)  NOT NULL UNIQUE
    , ORIGIN_NAME   VARCHAR2(1000)  NOT NULL
    , "SIZE"        VARCHAR2(100)   NOT NULL
);
