-------sej 데베 더미-----------


---상태
INSERT INTO STATE_A (NO, CONTENT)
VALUES (1, '등록');
INSERT INTO STATE_A (NO, CONTENT)
VALUES (2, '중지');
INSERT INTO STATE_A (NO, CONTENT)
VALUES (3, '해산');

INSERT INTO STATE_B (NO, CONTENT)
VALUES (1, '진행');
INSERT INTO STATE_B (NO, CONTENT)
VALUES (2, '중단');
INSERT INTO STATE_B (NO, CONTENT)
VALUES (3, '완료');
--일정 타입
DROP TABLE WORK_TYPE;

INSERT INTO WORK_TYPE (NO, NAME)
VALUES (1, '플젝 일정');
INSERT INTO WORK_TYPE (NO, NAME)
VALUES (2, '팀 일정');
INSERT INTO WORK_TYPE (NO, NAME)
VALUES (3, '개인 일정');

--프로젝트 담당자


INSERT INTO PROJECT_MANAGER (NO, PRO_NO, EMP_NO)
VALUES (SEQ_PROJECT_MANAGER.NEXTVAL, 1, 1 );
INSERT INTO PROJECT_MANAGER (NO, PRO_NO, EMP_NO)
VALUES (SEQ_PROJECT_MANAGER.NEXTVAL, 2, 2 );
INSERT INTO PROJECT_MANAGER (NO, PRO_NO, EMP_NO)
VALUES (SEQ_PROJECT_MANAGER.NEXTVAL, 3, 3 );

--플젝 일정
INSERT INTO PROJECT_WORK (NO,NO2,STATE_B_NO,TYPE_NO,START_DATE,TITLE,CONTENT)
VALUES (SEQ_PROJECT_WORK.NEXTVAL, 1, 1, 0, SYSDATE, '플젝일정1', '내용1');
INSERT INTO PROJECT_WORK (NO,NO2,STATE_B_NO,TYPE_NO,START_DATE,TITLE,CONTENT)
VALUES (SEQ_PROJECT_WORK.NEXTVAL, 2, 2, 0, SYSDATE, '플젝일정2', '내용2');


--기타일정
INSERT INTO PERSONAL _WORK (NO,NO2,STATE_B_NO,TYPE_NO,START_DATE,TITLE,CONTENT)
VALUES (SEQ_PERSONAL_WORK.NEXTVAL, 1, 1, 2, SYSDATE, '개인일정1', '내용1');
INSERT INTO PERSONAL _WORK (NO,NO2,STATE_B_NO,TYPE_NO,START_DATE,TITLE,CONTENT)
VALUES (SEQ_PERSONAL_WORK.NEXTVAL, 2, 2, 2, SYSDATE, '개인일정2', '내용2');
INSERT INTO PERSONAL _WORK (NO,NO2,STATE_B_NO,TYPE_NO,START_DATE,TITLE,CONTENT)
VALUES (SEQ_PERSONAL_WORK.NEXTVAL, 3, 3, 2, SYSDATE, '개인일정3', '내용3');

INSERT INTO PERSONAL _WORK (NO,NO2,STATE_B_NO,TYPE_NO,START_DATE,TITLE,CONTENT)
VALUES (SEQ_PERSONAL_WORK.NEXTVAL, 1, 1, 1, SYSDATE, '팀일정1', '내용1');
INSERT INTO PERSONAL _WORK (NO,NO2,STATE_B_NO,TYPE_NO,START_DATE,TITLE,CONTENT)
VALUES (SEQ_PERSONAL_WORK.NEXTVAL, 2, 2, 1, SYSDATE, '팀일정2', '내용2');
INSERT INTO PERSONAL _WORK (NO,NO2,STATE_B_NO,TYPE_NO,START_DATE,TITLE,CONTENT)
VALUES (SEQ_PERSONAL_WORK.NEXTVAL, 3, 3, 1, SYSDATE, '팀일정3', '내용3');

--플젝 정보
INSERT INTO PROJECT (NO,CODE,EMP_NO,STATE_A_NO,START_DATE, CONTENT)
VALUES (SEQ_PROJECT.NEXTVAL, 1, 1, 1, SYSDATE, '내용1');
INSERT INTO PROJECT (NO,CODE,EMP_NO,STATE_A_NO,START_DATE, CONTENT)
VALUES (SEQ_PROJECT.NEXTVAL, 2, 2, 2, SYSDATE, '내용1');
INSERT INTO PROJECT (NO,CODE,EMP_NO,STATE_A_NO,START_DATE, CONTENT)
VALUES (SEQ_PROJECT.NEXTVAL, 3, 3, 3, SYSDATE, '내용1');


--회의록
INSERT INTO CONFERENCE_RECORD (NO,PRJ_NO,ENL_DATE,CONTENT)
VALUES (SEQ_CONFERENCE_RECODE.NEXTVAL,1, SYSDATE,'아주끝내줌');
INSERT INTO CONFERENCE_RECORD (NO,PRJ_NO,ENL_DATE,CONTENT)
VALUES (SEQ_CONFERENCE_RECODE.NEXTVAL,2, SYSDATE,'그럭저럭');

--커밋
commit;


