----- LEAVE_TYPE -----
INSERT INTO LEAVE_TYPE(NO, NAME) VALUES(SEQ_LEAVE_TYPE.NEXTVAL, '연차');
INSERT INTO LEAVE_TYPE(NO, NAME) VALUES(SEQ_LEAVE_TYPE.NEXTVAL, '병가');
INSERT INTO LEAVE_TYPE(NO, NAME) VALUES(SEQ_LEAVE_TYPE.NEXTVAL, '경조사');

----- LEAVE -----
INSERT INTO LEAVE (
    NO, TYPE_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, STATE
) VALUES (
    SEQ_LEAVE.NEXTVAL, 1, 43, 13, '2024-06-03', '2024-06-05', '여름 휴가 사용', 1
);

INSERT INTO LEAVE (
    NO, TYPE_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, STATE
) VALUES (
    SEQ_LEAVE.NEXTVAL, 2, 43, 13, '2024-06-10', '2024-06-12', '식중독으로 인한 병가 사용', 1
);

INSERT INTO LEAVE (
    NO, TYPE_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, STATE
) VALUES (
    SEQ_LEAVE.NEXTVAL, 3, 43, 13, '2024-06-17', '2024-06-19', '외조부 장례로 인한 경조 휴가 사용', 1
);

INSERT INTO LEAVE (
    NO, TYPE_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, STATE
) VALUES (
    SEQ_LEAVE.NEXTVAL, 1, 43, 13, '2024-06-20', '2024-06-22', '기분 전환을 위한 연차 사용', 2
);

INSERT INTO LEAVE (
    NO, TYPE_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, STATE
) VALUES (
    SEQ_LEAVE.NEXTVAL, 2, 43, 13, '2024-06-25', '2024-06-27', '신장 수술로 인한 병가 사용', 0
);

INSERT INTO LEAVE (
    NO, TYPE_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, STATE
) VALUES (
    SEQ_LEAVE.NEXTVAL, 1, 43, 13, '2024-06-28', '2024-06-30', '가족 행사로 인한 연차 사용', 0
);

INSERT INTO LEAVE (
    NO, TYPE_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, STATE
) VALUES (
    SEQ_LEAVE.NEXTVAL, 1, 23, 13, '2024-06-01', '2024-06-03', '가족 여행으로 인한 연차 사용', 2
);

INSERT INTO LEAVE (
    NO, TYPE_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, STATE
) VALUES (
    SEQ_LEAVE.NEXTVAL, 2, 33, 13, '2024-06-05', '2024-06-07', '모발 이식으로 인한 병가 사용', 1
);

INSERT INTO LEAVE (
    NO, TYPE_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, STATE
) VALUES (
    SEQ_LEAVE.NEXTVAL, 3, 53, 13, '2024-06-10', '2024-06-12', '친조모 장례로 인한 휴가 사용', 1
);

INSERT INTO LEAVE (
    NO, TYPE_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, STATE
) VALUES (
    SEQ_LEAVE.NEXTVAL, 1, 23, 13, '2024-06-15', '2024-06-18', 'Refresh를 위한 연차 사용', 1
);

INSERT INTO LEAVE (
    NO, TYPE_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, STATE
) VALUES (
    SEQ_LEAVE.NEXTVAL, 1, 33, 13, '2024-06-20', '2024-06-22', '여름 휴가로 인한 연차 사용', 1
);

INSERT INTO LEAVE (
    NO, TYPE_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, STATE
) VALUES (
    SEQ_LEAVE.NEXTVAL, 1, 53, 13, '2024-06-25', '2024-06-27', '은행 업무를 위한 연차 사용', 0
);

----- BUSINESS_TRIP -----
-- 1 -> 43, 23
-- 2 -> 43, 33
-- 3 -> 53, 33
-- 4 -> 53, 23
INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 1, 43, 13, '2024-03-05', '2024-03-10', '고객 미팅 및 프로젝트 논의', '서울특별시 강남구 테헤란로 123', 1
);

INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 1, 43, 13, '2024-04-12', '2024-04-15', '기술 컨퍼런스 참석', '부산광역시 해운대구 해운대로 456', 2
);

INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 2, 43, 13, '2024-05-03', '2024-05-07', '신규 프로젝트 킥오프', '대구광역시 수성구 동대구로 789', 1
);

INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 1, 43, 13, '2024-06-01', '2024-06-05', '프로젝트 중간 점검', '인천광역시 남동구 인주대로 101', 1
);

INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 2, 43, 13, '2024-06-15', '2024-06-18', '고객사 워크샵 참석', '광주광역시 서구 상무대로 202', 2
);

INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 2, 43, 13, '2024-06-20', '2024-06-22', '해외 출장 준비', '서울특별시 중구 을지로 303', 0
);

INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 1, 43, 13, '2024-06-25', '2024-06-27', '프로젝트 마무리 미팅', '대전광역시 서구 둔산대로 404', 0
);

INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 1, 23, 13, '2024-03-05', '2024-03-10', '고객 미팅 및 프로젝트 논의', '서울특별시 강남구 테헤란로 123', 1
);

INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 2, 33, 13, '2024-03-15', '2024-03-20', '신제품 발표회 참석', '부산광역시 해운대구 해운대로 456', 2
);

INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 3, 53, 13, '2024-04-05', '2024-04-08', '기술 컨퍼런스 참석', '대구광역시 수성구 동대구로 789', 1
);

INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 4, 23, 13, '2024-04-20', '2024-04-25', '신규 프로젝트 킥오프', '인천광역시 남동구 인주대로 101', 1
);

INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 3, 33, 13, '2024-05-03', '2024-05-07', '프로젝트 중간 점검', '광주광역시 서구 상무대로 202', 2
);

INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 3, 53, 13, '2024-05-20', '2024-05-23', '고객사 워크샵 참석', '서울특별시 중구 을지로 303', 2
);

INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 4, 23, 13, '2024-06-01', '2024-06-05', '해외 출장 준비', '대전광역시 서구 둔산대로 404', 0
);

INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 2, 33, 13, '2024-06-10', '2024-06-13', '프로젝트 마무리 미팅', '울산광역시 남구 삼산로 505', 0
);

INSERT INTO BUSINESS_TRIP (
    NO, PRO_NO, EMP_NO, APPROVER_NO, START_DATE, END_DATE, REASON, DESTINATION, STATE
) VALUES (
    SEQ_BUSINESS_TRIP.NEXTVAL, 4, 53, 13, '2024-06-20', '2024-06-22', '내부 교육 및 세미나 참석', '수원시 영통구 영통로 606', 2
);

----- SIGN -----
INSERT INTO SIGN(
    NO, EMP_NO, RESULT, STEP, TITLE
    , CONTENT
) VALUES (
    SEQ_SIGN.NEXTVAL, 43, 0, 1, '신규 프로젝트 제안서 검토 요청',
    '본 제안서는 2024년도 하반기 신규 프로젝트에 대한 제안서로, 클라이언트 요구사항에 맞춘 다양한 솔루션을 포함하고 있습니다.
    본 프로젝트는 향후 6개월간 진행될 예정이며, 구체적인 일정과 예산안이 포함되어 있습니다.
    검토 부탁드립니다.'
);

INSERT INTO SIGN(
    NO, EMP_NO, RESULT, STEP, TITLE
    , CONTENT
) VALUES (
    SEQ_SIGN.NEXTVAL, 43, 1, 3, '2024년도 2분기 예산 승인 요청',
    '2024년도 2분기 예산안에 대한 승인 요청입니다.
    본 예산안에는 각 부서별 예산 배정 내역과 주요 프로젝트 예산이 포함되어 있으며, 전년도 예산 대비 증감 내역을 상세히 기술하였습니다.
    승인을 부탁드립니다.'
);

INSERT INTO SIGN(
    NO, EMP_NO, RESULT, STEP, TITLE
    , CONTENT
) VALUES (
    SEQ_SIGN.NEXTVAL, 43, 2, 3, '완료된 프로젝트에 대한 최종 보고서 및 마무리 문서',
    '본 문서는 최근 완료된 프로젝트의 최종 보고서입니다.
    프로젝트 목표 달성 여부, 주요 성과, 문제점 및 해결 방안, 향후 과제 등을 포함하고 있습니다.
    상세한 내용을 검토하신 후 최종 승인 부탁드립니다.'
);

INSERT INTO SIGN(
    NO, EMP_NO, RESULT, STEP, TITLE
    , CONTENT
) VALUES (
    SEQ_SIGN.NEXTVAL, 43, 0, 2, '2024년 하반기 연차 휴가 요청서',
    '2024년 하반기 연차 휴가에 대한 요청서입니다.
    휴가 기간은 2024년 7월 1일부터 2024년 7월 15일까지이며, 해당 기간 동안의 업무 인수인계 계획이 포함되어 있습니다.
    휴가 승인 부탁드립니다.'
);

INSERT INTO SIGN(
    NO, EMP_NO, RESULT, STEP, TITLE
    , CONTENT
) VALUES (
    SEQ_SIGN.NEXTVAL, 43, 2, 2, '신기술 교육 프로그램 참석 승인 요청',
    '신기술 교육 프로그램 참석에 대한 승인 요청입니다.
    교육 프로그램은 최신 기술 트렌드와 관련된 내용을 포함하고 있으며, 직원 역량 강화를 위해 필수적인 교육입니다.
    상세한 교육 일정과 내용이 포함된 자료를 첨부하였으니 검토 부탁드립니다.'
);

INSERT INTO SIGN(
    NO, EMP_NO, RESULT, STEP, TITLE
    , CONTENT
) VALUES (
    SEQ_SIGN.NEXTVAL, 43, 0, 3, '개발 팀 신규 장비 구매 요청서',
    '개발 팀에서 사용할 신규 장비에 대한 구매 요청서입니다.
    본 장비는 최신 개발 환경에 최적화된 사양을 갖추고 있으며, 생산성 향상에 크게 기여할 것으로 예상됩니다.
    상세 사양 및 견적서를 첨부하였으니 검토 부탁드립니다.'
);

INSERT INTO SIGN(
    NO, EMP_NO, RESULT, STEP, TITLE
    , CONTENT
) VALUES (
    SEQ_SIGN.NEXTVAL, 43, 1, 3, '사무실 리모델링 공사 제안서',
    '사무실 리모델링 공사에 대한 제안서입니다.
    본 공사는 직원들의 업무 환경 개선을 목표로 하며, 구체적인 공사 일정과 예산안이 포함되어 있습니다.
    리모델링 후 예상되는 효과와 상세한 공사 계획을 검토하신 후 승인을 부탁드립니다.'
);

INSERT INTO SIGN(
    NO, EMP_NO, RESULT, STEP, TITLE
    , CONTENT
) VALUES (
    SEQ_SIGN.NEXTVAL, 43, 1, 3, '고객사 감사 선물 구매 요청',
    '고객사에 대한 감사 선물 구매 요청입니다.
    고객사와의 장기적인 파트너십을 위해 감사 선물을 준비하고자 하며, 선물 목록과 예상 비용을 포함한 자료를 첨부하였습니다.
    승인을 부탁드립니다.'
);

INSERT INTO SIGN(
    NO, EMP_NO, RESULT, STEP, TITLE
    , CONTENT
) VALUES (
    SEQ_SIGN.NEXTVAL, 43, 0, 1, '팀 빌딩 워크숍 기획안',
    '팀 빌딩 워크숍에 대한 기획안입니다.
    워크숍은 팀원 간의 협업 강화와 소통 증진을 목표로 하며, 다양한 팀 빌딩 활동과 교육 프로그램이 포함되어 있습니다.
    상세한 일정과 비용이 포함된 기획안을 검토하신 후 승인을 부탁드립니다.'
);

----- SIGN_FILE -----
INSERT INTO SIGN_FILE(
    NO, SIGN_NO, CHANGE_NAME, ORIGIN_NAME, "SIZE", MODIFY_DATE
)
VALUES(
    SEQ_SIGN_FILE.NEXTVAL, 1, 'sign01.pdf', 'file01.pdf', 1200000, SYSDATE
);

INSERT INTO SIGN_FILE(
    NO, SIGN_NO, CHANGE_NAME, ORIGIN_NAME, "SIZE", MODIFY_DATE
)
VALUES(
    SEQ_SIGN_FILE.NEXTVAL, 2, 'sign02.pdf', 'file02.pdf', 1450000, SYSDATE
);

INSERT INTO SIGN_FILE(
    NO, SIGN_NO, CHANGE_NAME, ORIGIN_NAME, "SIZE", MODIFY_DATE
)
VALUES(
    SEQ_SIGN_FILE.NEXTVAL, 3, 'sign03.pdf', 'file03.pdf', 900000, SYSDATE
);

INSERT INTO SIGN_FILE(
    NO, SIGN_NO, CHANGE_NAME, ORIGIN_NAME, "SIZE", MODIFY_DATE
)
VALUES(
    SEQ_SIGN_FILE.NEXTVAL, 4, 'sign04.pdf', 'file04.pdf', 1130000, SYSDATE
);

INSERT INTO SIGN_FILE(
    NO, SIGN_NO, CHANGE_NAME, ORIGIN_NAME, "SIZE", MODIFY_DATE
)
VALUES(
    SEQ_SIGN_FILE.NEXTVAL, 5, 'sign05.pdf', 'file05.pdf', 870000, SYSDATE
);

INSERT INTO SIGN_FILE(
    NO, SIGN_NO, CHANGE_NAME, ORIGIN_NAME, "SIZE", MODIFY_DATE
)
VALUES(
    SEQ_SIGN_FILE.NEXTVAL, 6, 'sign06.pdf', 'file06.pdf', 1230000, SYSDATE
);

INSERT INTO SIGN_FILE(
    NO, SIGN_NO, CHANGE_NAME, ORIGIN_NAME, "SIZE", MODIFY_DATE
)
VALUES(
    SEQ_SIGN_FILE.NEXTVAL, 7, 'sign07.pdf', 'file07.pdf', 1740000, SYSDATE
);

INSERT INTO SIGN_FILE(
    NO, SIGN_NO, CHANGE_NAME, ORIGIN_NAME, "SIZE", MODIFY_DATE
)
VALUES(
    SEQ_SIGN_FILE.NEXTVAL, 8, 'sign08.pdf', 'file08.pdf', 957000, SYSDATE
);

INSERT INTO SIGN_FILE(
    NO, SIGN_NO, CHANGE_NAME, ORIGIN_NAME, "SIZE", MODIFY_DATE
)
VALUES(
    SEQ_SIGN_FILE.NEXTVAL, 9, 'sign09.pdf', 'file09.pdf', 998000, SYSDATE
);

----- SIGN_PATH -----
-- 6(부장), 13(팀장), 9(타팀장)
-- SIGN_NO 1
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 1, 13, 1);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 1, 9, 2);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 1, 6, 3);

-- SIGN_NO 2
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 2, 13, 1);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 2, 16, 2);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 2, 6, 3);

-- SIGN_NO 3
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 3, 13, 1);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 3, 18, 2);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 3, 6, 3);

-- SIGN_NO 4
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 4, 13, 1);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 4, 12, 2);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 4, 6, 3);

-- SIGN_NO 5
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 5, 13, 1);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 5, 11, 2);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 5, 6, 3);

-- SIGN_NO 6
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 6, 13, 1);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 6, 17, 2);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 6, 6, 3);

-- SIGN_NO 7
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 7, 13, 1);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 7, 15, 2);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 7, 6, 3);

-- SIGN_NO 8
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 8, 13, 1);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 8, 10, 2);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 8, 6, 3);

-- SIGN_NO 9
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 9, 13, 1);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 9, 14, 2);
INSERT INTO SIGN_PATH(NO, SIGN_NO, APPROVER_NO, SIGN_SEQ) VALUES(SEQ_SIGN_PATH.NEXTVAL, 9, 6, 3);

----- SIGN_REF -----
-- SIGN_NO 1
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 1, 4);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 1, 5);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 1, 7);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 1, 8);

-- SIGN_NO 2
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 2, 4);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 2, 5);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 2, 7);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 2, 8);

-- SIGN_NO 3
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 3, 4);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 3, 5);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 3, 7);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 3, 8);

-- SIGN_NO 4
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 4, 4);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 4, 5);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 4, 7);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 4, 8);

-- SIGN_NO 5
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 5, 4);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 5, 5);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 5, 7);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 5, 8);

-- SIGN_NO 6
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 6, 4);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 6, 5);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 6, 7);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 6, 8);

-- SIGN_NO 7
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 7, 4);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 7, 5);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 7, 7);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 7, 8);

-- SIGN_NO 8
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 8, 4);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 8, 5);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 8, 7);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 8, 8);

-- SIGN_NO 9
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 9, 4);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 9, 5);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 9, 7);
INSERT INTO SIGN_REF(NO, SIGN_NO, REF_NO) VALUES(SEQ_SIGN_REF.NEXTVAL, 9, 8);

----- SIGN_COM -----
-- SIGN_NO 2
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 2, '승인합니다. 납기 준수해주세요.');
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 2, '승인합니다. 클라이언트 요구사항 잘 파악해주세요.');
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 2, '승인합니다. 시간이 얼마 안 남은만큼 일정 관리 힘 써주세요.');

-- SIGN_NO 3
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 3, '승인합니다. 일정 조율 잘해주세요.');
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 3, '승인합니다. 형상 관리 신경 써주세요.');
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 3, '반려합니다. 타 프로젝트 일정과 겹칠 것 같습니다.');

-- SIGN_NO 4
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 4, '승인합니다. 이견 없습니다.');

-- SIGN_NO 5
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 5, '승인합니다. 타 팀과의 일정 조율 요청드립니다.');
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 5, '반려합니다. 우리 팀 일정 맞추기가 힘듭니다.');

-- SIGN_NO 6
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 6, '승인합니다. 프로젝트 진행 중 중간보고 바랍니다.');
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 6, '승인합니다. 일정 관리 잘해주세요.');

-- SIGN_NO 7
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 7, '승인합니다. 형상 관리 힘 써주세요.');
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 7, '승인합니다. 여러 팀이 관여하는 일이니, 형상 관리 힘 써주세요.');
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 7, '승인합니다. 타 팀과 유기적으로 협업할 수 있도록 신경 써주세요.');

-- SIGN_NO 8
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 8, '승인합니다. 이견 없습니다.');
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 8, '승인합니다. 이견 없습니다.');
INSERT INTO SIGN_COM(NO, SIGN_NO, "COMMENT") VALUES(SEQ_SIGN_COM.NEXTVAL, 8, '승인합니다. 이견 없습니다.');



--------------------------------------------------
--------------------------------------------------
--------------------------------------------------



asd



--------------------------------------------------
--------------------------------------------------
--------------------------------------------------



----- COMMIT -----
COMMIT;
