--TABLE 삭제
DROP TABLE PROJECT CASCADE CONSTRAINTS;
DROP TABLE PROJECT_MANAGER CASCADE CONSTRAINTS;
DROP TABLE CONFERENCE_RECODE CASCADE CONSTRAINTS;
DROP TABLE PROJECT_WORK CASCADE CONSTRAINTS;
DROP TABLE PERSONAL_WORK CASCADE CONSTRAINTS;
DROP TABLE CALENDER CASCADE CONSTRAINTS;

--SEQUENCE 삭제
DROP SEQUENCE SEQ_PROJECT_NO;
DROP SEQUENCE SEQ_PROJECT_MANAGER_NO;
DROP SEQUENCE SEQ_CONFERENCE_RECODE_NO;
DROP SEQUENCE SEQ_PROJECT_WORK__NO;
DROP SEQUENCE SEQ_PERSONAL_WORK_NO;
DROP SEQUENCE SEQ_PERSONAL_WORK_NO;

--SEQUENCE 생성
CREATE SEQUENCE SEQ_PROJECT_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PROJECT_MANAGER_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CONFERENCE_RECODE_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PROJECT_WORK__NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PERSONAL_WORK_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CALENDER_NO NOCACHE NOCYCLE;

--TABLE 생성
CREATE TABLE PROJECT(
    NO      NUMBER,
    CODE        NUMBER,
    EMP_NO      NUMBER,
    CONTENT     VARCHAR2(4000),
    START_DATE  DATE,
    END_DATE    DATE,
    MODIFY_DATE DATE,
    ING_YN      CHAR(1),
    STOP_YN     CHAR(1),
    COMPLETE_YN CHAR(1)
);


CREATE TABLE PROJECT_MANAGER(
    NO      NUMBER,
    PRO_NO  NUMBER,
    EMP_NO  NUMBER
);

CREATE TABLE CONFERENCE_RECODE(
    NO          NUMBER,
    PRJ_NO      NUMBER,
    ENL_DATE    DATE,
    ELE_DATE    DATE,
    ELE_YN      CHAR(1),
    TITLE       VARCHAR2(2000),
    CONTENT     VARCHAR2(4000),
    ING_YN      CHAR(1),
    STOP_YN     CHAR(1),
    COM_YN      CHAR(1)
);

CREATE TABLE PROJECT_WORK(
    NO          NUMBER,
    PRO_NO      NUMBER,
    ING_YN      CHAR(1),
    STOP_YN     CHAR(1),
    COM_YN      CHAR(1),
    START_DATE  DATE,
    END_DATE    DATE,
    MODIFY_DATE DATE,
    TITLE       VARCHAR2(2000),
    CONTENT     VARCHAR2(4000)
);


CREATE TABLE PERSONAL_WORK(
    NO          NUMBER,
    EMP_NO      NUMBER,
    ING_YN      CHAR(1),
    STOP_YN     CHAR(1),
    COM_YN      CHAR(1),
    START_DATE  DATE,
    END_DATE    DATE,
    MODIFY_DATE DATE,
    TITLE       VARCHAR2(2000),
    CONTENT     VARCHAR2(4000)
);

CREATE TABLE CALENDER(
    NO                  NUMBER,
    PERSONAL_WORK_NO    NUMBER,
    PROJECT_WORK_NO     NUMBER
)

--PROJECT(프로젝트 정보) 테이블 외래키
ALTER TABLE PROJECT
ADD CONSTRAINT PROJECT_CODE_FK
FOREIGN KEY(CODE) REFERENCES DEPARTMENT(CODE);

ALTER TABLE PROJECT 
ADD CONSTRAINT PROJECT_EMP_NO_FK
FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(NO);

--PROJECT-MANAGER(프로젝트담당자) 테이블 외래키
ALTER TABLE PROJECT_MANAGER 
ADD CONSTRAINT PROJECT_MANAGER_PRO_NO_FK
FOREIGN KEY(PRO_NO) REFERENCES PROJECT(NO);

ALTER TABLE PROJECT_MANAGER 
ADD CONSTRAINT PROJECT_MANAGER_EMP_NO_FK
FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(NO);

--CONFERENCE_RECORD(회의기록) 테이블 외레키
ALTER TABLE CONFERENCE_RECORD
ADD CONSTRAINT CONFERENCE_RECORD_PRJ_NO_FK
FOREIGN KEY(PRJ_NO) REFERENCES PROJECT(NO);

--PROJECT_WORK(프로젝트일정) 테이블 외래키
ALTER TABLE PROJECT_WORK
ADD CONSTRAINT PROJECT_WORK_PRJ_NO_FK
FOREIGN KEY(PRJ_NO) REFERENCES PROJECT(NO);

--PERSONAL_WORK(기타일정) 테이블 외래키
ALTER TABLE PERSONAL_WORK
ADD CONSTRAINT PERSONAL_WORK_EMP_NO_FK
FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(NO);

--CALENDER(일정) 테이블 외래키
ALTER TABLE CALENDER
ADD CONSTRAINT CALENDER_PERSONAL_WORK_NO_FK
FOREIGN KEY(PERSONAL_WORK_NO) REFERENCES PERSONAL_WORK(NO);

ALTER TABLE CALENDER
ADD CONSTRAINT CALENDER_PROJECT_WORK_NO_FK
FOREIGN KEY(PROJECT_WORK_NO) REFERENCES PROJECT_WORK(NO);


