SELECT E.NO, D.NAME AS DEPARTMENT, P.NAME AS POSITION, E.NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPT_CODE = D.CODE
JOIN POSITION P ON E.POSITION_CODE = P.CODE
;

SELECT E.NO, D.NAME AS DEPT_NAME, P.NAME AS POSITION_NAME, E.NAME, E.DEPT_CODE, E.POSITION_CODE, E.STATE, E.SALARY_CODE, E.RANK, E.SALARY, E.BONUS, E.ID, E.NICK, E.PHONE, E.ADDRESS, E.ENROLL_DATE, E.RETIRE_DATE, E.RETIRE_YN FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPT_CODE = D.CODE JOIN POSITION P ON E.POSITION_CODE = P.CODE;


SELECT NO, DEPT_CODE, POSITION_CODE FROM EMPLOYEE;