INSERT INTO COLLEAGE_EVAL (
                NO
                , EVALUATOR_NO
                , EVALUATEE_NO
                , POTENTIAL
                , COMMUNICATION
                , PROBLEM_SOLVE
                , RESPONSIBILITY
                , START_DATE
                , END_DATE
                , COMPLIMENT
                , DISAPPOINTMENT
                , SUGGESTION
            )
            VALUES (
                SEQ_COLLEAGE_EVAL.NEXTVAL
                , 30
                , 50
                , 30
                , 50
                , 60
                , 20
                , TO_TIMESTAMP('2024-07-08 09:00', 'YYYY-MM-DD HH24:MI')
                , TO_TIMESTAMP('2024-07-14 18:00', 'YYYY-MM-DD HH24:MI')
                , '칭찬할 점 없음'
                , '아쉬운 점 없음'
                , '하고픈 말도 없음'
            );

SELECT 
    C.NO
    , E.NAME AS EVALUATOR_NO
    , M.NAME AS EVALUATEE_NO
    , C.POTENTIAL
    , C.COMMUNICATION
    , C.PROBLEM_SOLVE
    , C.RESPONSIBILITY
    , C.COMPLIMENT
    , C.DISAPPOINTMENT
    , C.SUGGESTION
    , TO_CHAR(C.WRITE_DATE, 'YYYY-MM-DD') AS WRITE_DATE
FROM COLLEAGE_EVAL C
JOIN EMPLOYEE E
ON C.EVALUATOR_NO = E.NO
JOIN EMPLOYEE M
ON C.EVALUATEE_NO = M.NO
ORDER BY C.NO ASC
;

INSERT INTO LEADER_EVAL (
    NO
    , EVALUATOR_NO
    , EVALUATEE_NO
    , COMMUNICATION
    , RESPONSIBILITY
    , JUDGEMENT
    , PROFESSIONALISM
    , START_DATE
    , END_DATE
    , COMPLIMENT
    , DISAPPOINTMENT
    , SUGGESTION
)
VALUES (
    SEQ_LEADER_EVAL.NEXTVAL
    , #{EVALUATOR_NO}
    , #{EVALUATEE_NO}
    , #{COMMUNICATION}
    , #{RESPONSIBILITY}
    , #{JUDGEMENT}
    , #{PROFESSIONALISM}
    , '2024-07-06 09:00'
    , '2024-07-30 18:00'
    , #{COMPLIMENT}
    , #{DISAPPOINTMENT}
    , #{SUGGESTION}
)
;

SELECT 
    L.NO
    , E.NAME AS EVALUATOR_NO
    , M.NAME AS EVALUATEE_NO
    , L.COMMUNICATION
    , L.RESPONSIBILITY
    , L.JUDGEMENT
    , L.PROFESSIONALISM
    , L.COMPLIMENT
    , L.DISAPPOINTMENT
    , L.SUGGESTION
    , TO_CHAR(L.WRITE_DATE, 'YYYY-MM-DD') AS WRITE_DATE
FROM LEADER_EVAL L
JOIN EMPLOYEE E
ON L.EVALUATOR_NO = E.NO
JOIN EMPLOYEE M
ON L.EVALUATEE_NO = M.NO
ORDER BY L.NO ASC
;

SELECT *
FROM KPI
ORDER BY PROJECT_NO ASC
;

SELECT DISTINCT
    NO
    , EMP_NO
    , PROJECT_NO
    , GOAL
    , PERSONAL_SCHEDULE
    , ENROLL_DATE
    , MODIFY_DATE
    , FOCUS
FROM KPI
ORDER BY PROJECT_NO ASC;

INSERT INTO MEMBER_EVAL (
    NO
    , EVALUATOR_NO
    , EVALUATEE_NO
    , POTENTIAL
    , COMMUNICATION
    , PROBLEM_SOLVE
    , RESPONSIBILITY
    , START_DATE
    , END_DATE
    , COMPLIMENT
    , DISAPPOINTMENT
    , SUGGESTION
)VALUES (
    SEQ_MEMBER_EVAL.NEXTVAL
    , #{EVALUATOR_NO}
    , #{EVALUATEE_NO}
    , #{POTENTIAL}
    , #{COMMUNICATION}
    , #{PROBLEM_SOLVE}
    , #{RESPONSIBILITY}
    , '2024-07-02 09:00'
    , '2024-07-30 18:00'
    , #{COMPLIMENT}
    , #{DISAPPOINTMENT}
    , #{SUGGESTION}
)
;

SELECT 
    M.NO
    , E.NAME AS EVALUATOR_NO
    , P.NAME AS EVALUATEE_NO
    , M.POTENTIAL
    , M.COMMUNICATION
    , M.PROBLEM_SOLVE
    , M.RESPONSIBILITY
    , M.COMPLIMENT
    , M.DISAPPOINTMENT
    , M.SUGGESTION
    , TO_CHAR(M.WRITE_DATE, 'YYYY-MM-DD') AS WRITE_DATE
FROM MEMBER_EVAL M
JOIN EMPLOYEE E
ON M.EVALUATOR_NO = E.NO
JOIN EMPLOYEE P
ON M.EVALUATEE_NO = P.NO
ORDER BY M.NO ASC
;

SELECT
    E.NAME AS EVALUATOR_NO
    , P.NAME AS EVALUATEE_NO
FROM MEMBER_EVAL M
JOIN EMPLOYEE E
ON M.EVALUATOR_NO = E.NO
JOIN EMPLOYEE P
ON M.EVALUATEE_NO = P.NO
;

SELECT
    NAME
FROM EMPLOYEE
;

SELECT
     E.NAME
FROM LEADER_EVAL L
JOIN EMPLOYEE E
ON L.EVALUATOR_NO = E.NO
JOIN EMPLOYEE P
ON L.EVALUATEE_NO = P.NO
WHERE L.EVALUATOR_NO = 41 
;

-- 평가한대상 제외 팀장평가리스트
SELECT 
    E.NAME
FROM EMPLOYEE E
JOIN LEADER_EVAL L
ON L.EVALUATEE_NO = E.NO
WHERE E.DEPT_CODE = 30
AND E.POSITION_CODE = 40
AND L.EVALUATEE_NO NOT IN 
(SELECT
    EVALUATEE_NO
FROM LEADER_EVAL)
;

-- 동료평가리스트
SELECT 
    NAME
FROM EMPLOYEE 
WHERE DEPT_CODE = (
SELECT
    DEPT_CODE
FROM EMPLOYEE
WHERE NO = 43
)
AND POSITION_CODE = (
SELECT
    POSITION_CODE
FROM EMPLOYEE
WHERE NO = 43
)
;

SELECT
    EVALUATEE_NO
FROM COLLEAGE_EVAL;

SELECT
    E.NO
FROM EMPLOYEE E
JOIN COLLEAGE_EVAL C
ON 
WHERE C.EVALUATEE_NO NOT IN 
(SELECT
    C.EVALUATEE_NO
FROM COLLEAGE_EVAL);

SELECT
    NAME
FROM EMPLOYEE
WHERE DEPT_CODE = 20
;

-- 43번의 부서코드
SELECT
    E.DEPT_CODE
FROM EMPLOYEE E
JOIN COLLEAGE_EVAL C
ON E.NO = C.EVALUATOR_NO
WHERE C.EVALUATOR_NO = 43
;

-- 43번과 같은 직급
SELECT
    E.POSITION_CODE
FROM EMPLOYEE E
JOIN COLLEAGE_EVAL C
ON E.NO = C.EVALUATOR_NO
WHERE C.EVALUATOR_NO = 43
;

-- 출근시간 
INSERT INTO COMMUTE (NO, EMP_NO, WORK_TIME) VALUES (SEQ_COMMUTE.NEXTVAL, 3, SYSDATE);

-- 퇴근시간
UPDATE COMMUTE
SET QUIT_TIME = SYSDATE
WHERE EMP_NO = 3 AND WORK_TIME = (
    SELECT MAX(WORK_TIME) 
    FROM COMMUTE 
    WHERE EMP_NO = 3
)
;

