SELECT
    E.NO
    , E.NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D
ON E.DEPT_CODE = D.CODE
WHERE (E.DEPT_CODE = 
(SELECT 
    DEPT_CODE
FROM EMPLOYEE
WHERE NO = 43)
OR E.DIV_CODE = 
(SELECT
    DIV_CODE
FROM EMPLOYEE
WHERE NO = 43))
AND E.NO != 43
AND E.NO NOT IN (
    SELECT EVALUATEE_NO FROM LEADER_EVAL WHERE EVALUATOR_NO = 43
    UNION
    SELECT EVALUATEE_NO FROM MEMBER_EVAL WHERE EVALUATOR_NO = 43
    UNION
    SELECT EVALUATEE_NO FROM COLLEAGE_EVAL WHERE EVALUATOR_NO = 43
)
;