----- 시퀀스 삭제 -----
DROP SEQUENCE SEQ_SIGN;
DROP SEQUENCE SEQ_SIGN_FILE;
DROP SEQUENCE SEQ_SIGN_PATH;
DROP SEQUENCE SEQ_SIGN_REF;
DROP SEQUENCE SEQ_SIGN_COM;
DROP SEQUENCE SEQ_LEAVE;
DROP SEQUENCE SEQ_BUSINESS_TRIP;
DROP SEQUENCE SEQ_LEAVE_TYPE;



----- 테이블 삭제 -----
DROP TABLE SIGN CASCADE CONSTRAINTS;
DROP TABLE SIGN_FILE CASCADE CONSTRAINTS;
DROP TABLE SIGN_PATH CASCADE CONSTRAINTS;
DROP TABLE SIGN_REF CASCADE CONSTRAINTS;
DROP TABLE SIGN_COM CASCADE CONSTRAINTS;
DROP TABLE LEAVE CASCADE CONSTRAINTS;
DROP TABLE BUSINESS_TRIP CASCADE CONSTRAINTS;
DROP TABLE LEAVE_TYPE CASCADE CONSTRAINTS;



----- 시퀀스 생성 -----
CREATE SEQUENCE SEQ_SIGN NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SIGN_FILE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SIGN_PATH NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SIGN_REF NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SIGN_COM NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LEAVE NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BUSINESS_TRIP NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_LEAVE_TYPE NOCACHE NOCYCLE;



----- 테이블 생성 -----
CREATE TABLE SIGN(
    NO              NUMBER          PRIMARY KEY
    , EMP_NO        NUMBER          NOT NULL
    , RESULT        NUMBER          NOT NULL
    , STEP          NUMBER          NOT NULL
    , TITLE         VARCHAR2(1000)  NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
);
CREATE TABLE SIGN_FILE(
    NO              NUMBER          PRIMARY KEY
    , SIGN_NO       NUMBER          NOT NULL
    , CHANGE_NAME   VARCHAR2(1000)  NOT NULL UNIQUE
    , ORIGIN_NAME   VARCHAR2(1000)  NOT NULL
    , "SIZE"        NUMBER          NOT NULL
    , MODIFY_DATE   TIMESTAMP       DEFAULT SYSDATE
);
CREATE TABLE SIGN_PATH(
    NO              NUMBER          PRIMARY KEY
    , SIGN_NO       NUMBER          NOT NULL
    , APPROVER_NO   NUMBER          NOT NULL
    , SIGN_SEQ      NUMBER          NOT NULL
);
CREATE TABLE SIGN_REF(
    NO              NUMBER          PRIMARY KEY
    , SIGN_NO       NUMBER          NOT NULL
    , REF_NO        NUMBER          NOT NULL
);
CREATE TABLE SIGN_COM(
    NO              NUMBER          PRIMARY KEY
    , SIGN_NO       NUMBER          NOT NULL
    , "COMMENT"     VARCHAR2(4000)
);
CREATE TABLE LEAVE(
    NO              NUMBER          PRIMARY KEY
    , SIGN_NO       NUMBER          NOT NULL
    , TYPE_NO       NUMBER          NOT NULL
    , START_DATE    TIMESTAMP       NOT NULL
    , END_DATE      TIMESTAMP       NOT NULL
    , REASON        VARCHAR2(4000)  NOT NULL
);
CREATE TABLE BUSINESS_TRIP(
    NO              NUMBER          PRIMARY KEY
    , PRO_NO        NUMBER          NOT NULL
    , SIGN_NO       NUMBER          NOT NULL
    , START_DATE    TIMESTAMP       NOT NULL
    , END_DATE      TIMESTAMP       NOT NULL
    , REASON        VARCHAR2(4000)  NOT NULL
    , DESTINATION   VARCHAR2(1000)  NOT NULL
);
CREATE TABLE LEAVE_TYPE(
    NO              NUMBER          PRIMARY KEY
    , NAME          VARCHAR2(20)    NOT NULL
);



----- 외래키 추가 -----
ALTER TABLE LEAVE
ADD CONSTRAINT FK_LEAVE_SIGN
FOREIGN KEY (SIGN_NO)
REFERENCES SIGN(NO);

ALTER TABLE LEAVE
ADD CONSTRAINT FK_LEAVE_LEAVE_TYPE
FOREIGN KEY (TYPE_NO)
REFERENCES LEAVE_TYPE(NO);

ALTER TABLE BUSINESS_TRIP
ADD CONSTRAINT FK_BUSINESS_TRIP_PROJECT
FOREIGN KEY (PRO_NO)
REFERENCES PROJECT(NO);

ALTER TABLE BUSINESS_TRIP
ADD CONSTRAINT FK_BUSINESS_TRIP_SIGN
FOREIGN KEY (SIGN_NO)
REFERENCES SIGN(NO);

ALTER TABLE SIGN
ADD CONSTRAINT FK_SIGN_EMPLOYEE
FOREIGN KEY (EMP_NO)
REFERENCES EMPLOYEE(NO);

ALTER TABLE SIGN_FILE
ADD CONSTRAINT FK_SIGN_FILE_SIGN
FOREIGN KEY (SIGN_NO)
REFERENCES SIGN(NO);

ALTER TABLE SIGN_PATH
ADD CONSTRAINT FK_SIGN_PATH_SIGN
FOREIGN KEY (SIGN_NO)
REFERENCES SIGN(NO);

ALTER TABLE SIGN_PATH
ADD CONSTRAINT FK_SIGN_PATH_EMPLOYEE
FOREIGN KEY (APPROVER_NO)
REFERENCES EMPLOYEE(NO);

ALTER TABLE SIGN_REF
ADD CONSTRAINT FK_SIGN_REF_SIGN
FOREIGN KEY (SIGN_NO)
REFERENCES SIGN(NO);

ALTER TABLE SIGN_REF
ADD CONSTRAINT FK_SIGN_REF_EMPLOYEE
FOREIGN KEY (REF_NO)
REFERENCES EMPLOYEE(NO);

ALTER TABLE SIGN_COM
ADD CONSTRAINT FK_SIGN_COM_SIGN
FOREIGN KEY (SIGN_NO)
REFERENCES SIGN(NO);



----- 메일 -----
DROP SEQUENCE SEQ_MAIL;
DROP SEQUENCE SEQ_MAIL_AD;
DROP SEQUENCE SEQ_MAIL_INFO;
DROP SEQUENCE SEQ_MAIL_FILE;

DROP TABLE MAIL CASCADE CONSTRAINTS;
DROP TABLE MAIL_AD CASCADE CONSTRAINTS;
DROP TABLE MAIL_INFO CASCADE CONSTRAINTS;
DROP TABLE MAIL_FILE CASCADE CONSTRAINTS;

CREATE SEQUENCE SEQ_MAIL NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MAIL_AD NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MAIL_INFO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MAIL_FILE NOCACHE NOCYCLE;

CREATE TABLE MAIL(
    NO              NUMBER          PRIMARY KEY
    , MAIL_INFO_NO  NUMBER          NOT NULL
    , TYPE          VARCHAR2(20)    NOT NULL
    , SUBJECT       VARCHAR2(1000)  NOT NULL
    , CONTENT       VARCHAR2(4000)  NOT NULL
    , "FROM"        VARCHAR2(20)    NOT NULL
    , READ_DATE     TIMESTAMP
    , WRITE_DATE    TIMESTAMP       DEFAULT SYSDATE
    , DEL_YN        CHAR(1)         DEFAULT 'N' CHECK (DEL_YN IN ('Y', 'N'))
);
CREATE TABLE MAIL_AD(
    NO              NUMBER          PRIMARY KEY
    , MAIL_NO       NUMBER          NOT NULL
    , ADDRESS       CHAR(20)        NOT NULL
    , TYPE          VARCHAR2(20)    NOT NULL
);
CREATE TABLE MAIL_INFO(
    NO              NUMBER          PRIMARY KEY
    , EMP_NO        NUMBER          NOT NULL
    , IMAP_AD       VARCHAR2(1000)  NOT NULL
    , IMAP_PORT     VARCHAR2(1000)  NOT NULL
    , SMTP_AD       VARCHAR2(1000)  NOT NULL
    , SMTP_PORT     VARCHAR2(1000)  NOT NULL
    , ACCOUNT       CHAR(20)        NOT NULL
    , PWD           CHAR(15)        NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
);
CREATE TABLE MAIL_FILE(
    NO              NUMBER          PRIMARY KEY
    , MAIL_NO       NUMBER          NOT NULL
    , CHANGE_NAME   VARCHAR2(100)   NOT NULL UNIQUE
    , ORIGIN_NAME   VARCHAR2(100)   NOT NULL
    , "SIZE"        NUMBER          NOT NULL
);

ALTER TABLE MAIL
ADD CONSTRAINT FK_MAIL_MAIL_INFO
FOREIGN KEY (MAIL_INFO_NO)
REFERENCES MAIL_INFO(NO);

ALTER TABLE MAIL_AD
ADD CONSTRAINT FK_MAIL_AD_MAIL
FOREIGN KEY (MAIL_NO)
REFERENCES MAIL(NO);

ALTER TABLE MAIL_INFO
ADD CONSTRAINT FK_MAIL_INFO_EMPLOYEE
FOREIGN KEY (EMP_NO)
REFERENCES EMPLOYEE(NO);

ALTER TABLE MAIL_FILE
ADD CONSTRAINT FK_MAIL_FILE_MAIL
FOREIGN KEY (MAIL_NO)
REFERENCES MAIL(NO);
