--TABLE 삭제
DROP TABLE PROJECT CASCADE CONSTRAINTS;
DROP TABLE PROJECT_MANAGER CASCADE CONSTRAINTS;
DROP TABLE CONFERENCE_RECODE CASCADE CONSTRAINTS;
DROP TABLE PROJECT_WORK CASCADE CONSTRAINTS;
DROP TABLE PERSONAL_WORK CASCADE CONSTRAINTS;
DROP TABLE WORK_TYPE CASCADE CONSTRAINTS;
DROP TABLE STATE_A CASCADE CONSTRAINTS;
DROP TABLE STATE_B CASCADE CONSTRAINTS;

--SEQUENCE 삭제
DROP SEQUENCE SEQ_PROJECT_NO;
DROP SEQUENCE SEQ_PROJECT_MANAGER_NO;
DROP SEQUENCE SEQ_CONFERENCE_RECODE_NO;
DROP SEQUENCE SEQ_PROJECT_WORK__NO;
DROP SEQUENCE SEQ_PERSONAL_WORK_NO;
DROP SEQUENCE SEQ_WORK_TYPE_NO;
DROP SEQUENCE SEQ_STATE_A_NO;
DROP SEQUENCE SEQ_STATE_B_NO;
--SEQUENCE 생성
CREATE SEQUENCE SEQ_PROJECT_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PROJECT_MANAGER_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CONFERENCE_RECODE_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PROJECT_WORK__NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PERSONAL_WORK_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_WORK_TYPE_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_STATE_A_NO NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_STATE_B_NO NOCACHE NOCYCLE;

--TABLE 생성
CREATE TABLE PROJECT(
    NO          NUMBER          PRIMARY KEY,
    CODE        NUMBER          ,
    EMP_NO      NUMBER          ,
    STATE_A_NO  NUMBER          ,
    CONTENT     VARCHAR2(4000)  NOT NULL,
    START_DATE  TIMESTAMP       DEFAULT SYSDATE,
    END_DATE    TIMESTAMP   ,
    MODIFY_DATE TIMESTAMP
);


CREATE TABLE PROJECT_MANAGER(
    NO      NUMBER      PRIMARY KEY,
    PRO_NO  NUMBER      ,
    EMP_NO  NUMBER   
);

CREATE TABLE CONFERENCE_RECODE(
    NO          NUMBER          PRIMARY KEY,
    PRJ_NO      NUMBER          ,
    ENL_DATE    TIMESTAMP       DEFAULT SYSDATE,
    DEL_YN      CHAR(1)         DEFAULT 'N' CHECK (DEL_YN IN('Y','N')),
    TITLE       VARCHAR2(2000)  NOT NULL,
    CONTENT     VARCHAR2(4000)  NOT NULL
);

CREATE TABLE PROJECT_WORK(
    NO              NUMBER          PRIMARY KEY,
    NO2             NUMBER          UNIQUE NOT NULL,
    STATE_B_NO      NUMBER          ,
    TYPE_NO         NUMBER          ,
    START_DATE      TIMESTAMP       DEFAULT SYSDATE,
    END_DATE        TIMESTAMP,
    MODIFY_DATE     TIMESTAMP,
    TITLE           VARCHAR2(2000)  NOT NULL,
    CONTENT         VARCHAR2(4000)  NOT NULL
);

CREATE TABLE WORK_TYPE(
    NO          NUMBER          PRIMARY KEY,
    NAME        VARCHAR2(10)    NOT NULL
);

CREATE TABLE PERSONAL_WORK(
    NO              NUMBER      PRIMARY KEY,
    NO2             NUMBER      UNIQUE NOT NULL,
    STATE_B_NO      NUMBER      ,
    TYPE_NO         NUMBER      ,
    START_DATE      TIMESTAMP   DEFAULT SYSDATE,
    END_DATE        TIMESTAMP,
    MODIFY_DATE     TIMESTAMP,
    TITLE       VARCHAR2(2000)  NOT NULL,
    CONTENT     VARCHAR2(4000)  NOT NULL
);

CREATE TABLE STATE_A(
    NO          NUMBER          PRIMARY KEY,
    CONTENT     VARCHAR2(100)   NOT NULL   
);

CREATE TABLE STATE_B(
    NO          NUMBER          PRIMARY KEY,
    CONTENT     VARCHAR2(100)   NOT NULL
);


--PROJECT(프로젝트 정보) 테이블 외래키
ALTER TABLE PROJECT
ADD CONSTRAINT PROJECT_CODE_FK
FOREIGN KEY(CODE) REFERENCES DEPARTMENT(CODE);

ALTER TABLE PROJECT 
ADD CONSTRAINT PROJECT_EMP_NO_FK
FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(NO);

ALTER TABLE PROJECT
ADD CONSTRAINT PROJECT_STATE_A_NO_FK
FOREIGN KEY(STATE_A_NO) REFERENCES STATE_A(NO);

--PROJECT-MANAGER(프로젝트담당자) 테이블 외래키
ALTER TABLE PROJECT_MANAGER 
ADD CONSTRAINT PROJECT_MANAGER_PRO_NO_FK
FOREIGN KEY(PRO_NO) REFERENCES PROJECT(NO);

ALTER TABLE PROJECT_MANAGER 
ADD CONSTRAINT PROJECT_MANAGER_EMP_NO_FK
FOREIGN KEY(EMP_NO) REFERENCES EMPLOYEE(NO);

--CONFERENCE_RECORD(회의기록) 테이블 외레키
ALTER TABLE CONFERENCE_RECORD
ADD CONSTRAINT CONFERENCE_RECORD_PRJ_NO_FK
FOREIGN KEY(PRJ_NO) REFERENCES PROJECT(NO);

--PROJECT_WORK(프로젝트일정) 테이블 외래키
ALTER TABLE PROJECT_WORK
ADD CONSTRAINT PROJECT_WORK_NO2_FK
FOREIGN KEY(NO2) REFERENCES PROJECT(NO);

ALTER TABLE PROJECT_WORK
ADD CONSTRAINT PROJECT_WORK_STATE_B_NO_FK
FOREIGN KEY(STATE_B_NO) REFERENCES STATE_B(NO);

ALTER TABLE PROJECT_WORK
ADD CONSTRAINT PROJECT_WORK_TYPE_NO_FK
FOREIGN KEY(TYPE_NO) REFERENCES WORK_TYPE(NO);

--PERSONAL_WORK(기타일정) 테이블 외래키
ALTER TABLE PERSONAL_WORK
ADD CONSTRAINT PERSONAL_WORK_NO2_FK
FOREIGN KEY(NO2) REFERENCES EMPLOYEE(NO);

ALTER TABLE PERSONAL_WORK
ADD CONSTRAINT PERSONAL_WORK_STATE_B_NO_FK
FOREIGN KEY(STATE_B_NO) REFERENCES STATE_B(NO);

ALTER TABLE PERSONAL_WORK
ADD CONSTRAINT PERSONAL_WORK_TYPE_NO_FK
FOREIGN KEY(TYPE_NO) REFERENCES WORK_TYPE(NO);

