SELECT E.NO, D.NAME AS DEPARTMENT, P.NAME AS POSITION, E.NAME
FROM EMPLOYEE E
JOIN DEPARTMENT D ON E.DEPT_CODE = D.CODE
JOIN POSITION P ON E.POSITION_CODE = P.CODE
;

SELECT E.NO, D.NAME AS DEPT_NAME, P.NAME AS POSITION_NAME, E.NAME, E.DEPT_CODE, E.POSITION_CODE, E.STATE, E.SALARY_CODE, E.RANK, E.SALARY, E.BONUS, E.ID, E.NICK, E.PHONE, E.ADDRESS, E.ENROLL_DATE, E.RETIRE_DATE, E.RETIRE_YN FROM EMPLOYEE E JOIN DEPARTMENT D ON E.DEPT_CODE = D.CODE JOIN POSITION P ON E.POSITION_CODE = P.CODE;


SELECT NO, DEPT_CODE, POSITION_CODE FROM EMPLOYEE;

SELECT * FROM EMPLOYEE WHERE DIV_CODE = 20241001;
SELECT * FROM DIVISION WHERE CODE = 20241001;

SELECT
DIV.CODE
, DIV.DEPT_CODE
, DIV.NAME
, DIV.STATE
, DIV.ENROLL_DATE
, DIV.MODIFY_DATE
, DIV.END_DATE
, DEPT.NAME
FROM DIVISION DIV
JOIN DEPARTMENT DEPT ON DIV.DEPT_CODE = DEPT.CODE;


SELECT TO_CHAR(M.SEND_TIME, 'YYYY/MM/DD HH:MM') AS SEND_TIME, M.SENDER, M.RECEIVER, M.TITLE, DEPT.NAME AS DEPT_NAME, DIV.NAME AS DIV_NAME, P.NAME AS POSITION_NAME, SENDER_EMP.NAME AS SENDER_NAME, RECEIVER_EMP.NAME AS RECEIVER_NAME
FROM MESSAGE M
JOIN EMPLOYEE EMP ON EMP.NO = M.RECEIVER
JOIN EMPLOYEE SENDER_EMP ON M.SENDER = SENDER_EMP.NO
JOIN EMPLOYEE RECEIVER_EMP ON M.RECEIVER = RECEIVER_EMP.NO
JOIN DEPARTMENT DEPT ON EMP.DEPT_CODE = DEPT.CODE
JOIN DIVISION DIV ON EMP.DIV_CODE = DIV.CODE
JOIN POSITION P ON EMP.POSITION_CODE = P.CODE
WHERE SENDER = 1
ORDER BY M.SEND_TIME DESC
;

SELECT
    TO_CHAR(M.SEND_TIME, 'YYYY/MM/DD HH24:MI') AS SEND_TIME
    , M.TITLE
    , M.SENDER
    , M.RECEIVER
    , M.READ_YN
    , M.DEL_YN
    , SENDER_EMP.NAME AS SENDER_NAME
    , RECEIVER_EMP.NAME AS RECEIVER_NAME
    , SENDER_DEPT.NAME AS SENDER_DEPT_NAME
    , SENDER_DIV.NAME AS SENDER_DIV_NAME
    , SENDER_POSITION.NAME AS SENDER_POSITION_NAME
    , RECEIVER_DEPT.NAME AS RECEIVER_DEPT_NAME
    , RECEIVER_DIV.NAME AS RECEIVER_DIV_NAME
    , RECEIVER_POSITION.NAME AS RECEIVER_POSITION_NAME
FROM MESSAGE M
JOIN EMPLOYEE SENDER_EMP ON M.SENDER = SENDER_EMP.NO
JOIN DEPARTMENT SENDER_DEPT ON SENDER_EMP.DEPT_CODE = SENDER_DEPT.CODE
JOIN DIVISION SENDER_DIV ON SENDER_EMP.DIV_CODE = SENDER_DIV.CODE
JOIN POSITION SENDER_POSITION ON SENDER_EMP.POSITION_CODE = SENDER_POSITION.CODE
JOIN EMPLOYEE RECEIVER_EMP ON M.RECEIVER = RECEIVER_EMP.NO
JOIN DEPARTMENT RECEIVER_DEPT ON RECEIVER_EMP.DEPT_CODE = RECEIVER_DEPT.CODE
JOIN DIVISION RECEIVER_DIV ON RECEIVER_EMP.DIV_CODE = RECEIVER_DIV.CODE
JOIN POSITION RECEIVER_POSITION ON RECEIVER_EMP.POSITION_CODE = RECEIVER_POSITION.CODE
WHERE M.SENDER = 1
ORDER BY M.SEND_TIME DESC
;

SELECT COUNT(*)
FROM MESSAGE
WHERE SENDER = 1;
